import {
  Company,
  Client,
  Enquiry,
  Profile,
  TeamMember,
  Editor,
  Project,
  ProjectTeamAssignment,
  ProjectData,
  Deliverable,
  Payment,
  Expense,
  CalendarEvent,
  AppNotification,
} from '../types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'twb',
    code: 'twb',
    name: 'TWB (The Wedding Book)',
    tagline: 'Modern Editorial Wedding Cinematography & Stills',
    email: 'hello@twbfilms.com',
    phone: '+1 (415) 890-2341',
    website: 'https://twbfilms.com',
    address: 'Studio 402, 180 Townsend St, San Francisco, CA 94107',
    primary_color: '#0f172a',
    accent_color: '#2563eb',
    bank_details: {
      account_name: 'The Wedding Book Media LLC',
      account_number: '9840-2391-4402',
      bank_name: 'Silicon Valley Bank / First Republic',
      routing_code: '121000358',
    },
    terms_conditions: '50% retainer required upon booking confirmation. Remaining balance due 14 days prior to wedding date. Raw archival footage maintained for 180 days post final delivery.',
  },
  {
    id: 'golden_june',
    code: 'golden_june',
    name: 'Golden June Studios',
    tagline: 'Warm, Nostalgic & Timeless Wedding Cinema',
    email: 'contact@goldenjunestudios.com',
    phone: '+1 (212) 674-8890',
    website: 'https://goldenjunestudios.com',
    address: 'Suite 8B, 45 Crosby Street, SoHo, New York, NY 10012',
    primary_color: '#3b2207',
    accent_color: '#d97706',
    bank_details: {
      account_name: 'Golden June Creative Inc.',
      account_number: '4410-8829-1093',
      bank_name: 'Chase Manhattan Commercial',
      routing_code: '021000021',
    },
    terms_conditions: 'Retainer deposit of 40% secures date exclusivity. 30% midpoint milestone, 30% on completion. Color grading revision rounds capped at 2 iterations per agreement.',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'p-1',
    email: 'admin@twbhub.internal',
    full_name: 'Julian Montgomery',
    role: 'Admin',
    phone: '+1 (415) 555-0100',
    company_id: 'both',
    status: 'Active',
  },
  {
    id: 'p-2',
    email: 'maya.ops@twbhub.internal',
    full_name: 'Maya Lin',
    role: 'Manager',
    phone: '+1 (415) 555-0101',
    company_id: 'both',
    status: 'Active',
  },
  {
    id: 'p-3',
    email: 'alex.camera@twbhub.internal',
    full_name: 'Alex Rivera',
    role: 'Team Member',
    phone: '+1 (415) 555-0102',
    company_id: 'twb',
    status: 'Active',
  },
  {
    id: 'p-4',
    email: 'marcus.edit@twbhub.internal',
    full_name: 'Marcus Vance',
    role: 'Editor',
    phone: '+1 (415) 555-0103',
    company_id: 'both',
    status: 'Active',
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@twbfilms.com',
    phone: '+1 (415) 555-0102',
    role_title: 'Lead Cinematographer',
    skills: ['Director of Photography', 'Sony FX6 / FX3', 'Gimbal Op', 'Drone FAA 107'],
    is_active: true,
    daily_rate: 1200,
    notes: 'Primary director for high-profile destination weddings.',
  },
  {
    id: 'tm-2',
    name: 'Sarah Jenkins',
    email: 'sarah.j@goldenjunestudios.com',
    phone: '+1 (415) 555-0144',
    role_title: 'Principal Editorial Photographer',
    skills: ['Editorial Stills', 'Medium Format Digital', '35mm Film', 'Leica M'],
    is_active: true,
    daily_rate: 1100,
    notes: 'Specializes in natural light Golden June aesthetics.',
  },
  {
    id: 'tm-3',
    name: 'David Patel',
    email: 'david.p@twbfilms.com',
    phone: '+1 (415) 555-0198',
    role_title: 'Second Cinematographer & Audio Tech',
    skills: ['2nd Camera', '32-bit Float Multi-track Audio', 'Ronin 4D'],
    is_active: true,
    daily_rate: 850,
    notes: 'Flawless ceremony audio and wireless lav management.',
  },
  {
    id: 'tm-4',
    name: 'Nina Chen',
    email: 'nina.c@goldenjunestudios.com',
    phone: '+1 (415) 555-0211',
    role_title: 'Second Photographer & Drone Op',
    skills: ['Secondary Coverage', 'Drone Aerials', 'Flash Lighting'],
    is_active: true,
    daily_rate: 800,
    notes: 'Certified Part 107 pilot for estate & coastal flyovers.',
  },
  {
    id: 'tm-5',
    name: 'Kai Tanaka',
    email: 'kai.t@twbfilms.com',
    phone: '+1 (415) 555-0322',
    role_title: 'Camera Assistant & DIT',
    skills: ['Data Ingestion', 'Silverstack Checksum Offload', 'Lens Tech'],
    is_active: true,
    daily_rate: 650,
    notes: 'On-site triple redundancy backup specialist.',
  },
];

export const INITIAL_EDITORS: Editor[] = [
  {
    id: 'ed-1',
    name: 'Marcus Vance',
    email: 'marcus.edit@twbhub.internal',
    phone: '+1 (415) 555-0103',
    specialization: 'Cinematography',
    is_active: true,
    max_concurrent_projects: 3,
    notes: 'Senior feature film and ceremony lead editor.',
  },
  {
    id: 'ed-2',
    name: 'Chloe Laurent',
    email: 'chloe.color@twbhub.internal',
    phone: '+1 (415) 555-0155',
    specialization: 'Colorist',
    is_active: true,
    max_concurrent_projects: 4,
    notes: 'DaVinci Resolve studio colorist; master of Golden June warm grain tone.',
  },
  {
    id: 'ed-3',
    name: 'Tyler Brooks',
    email: 'tyler.teaser@twbhub.internal',
    phone: '+1 (415) 555-0177',
    specialization: 'Cinematography',
    is_active: true,
    max_concurrent_projects: 3,
    notes: 'Fast-turnaround high-energy highlight films & Instagram reels.',
  },
  {
    id: 'ed-4',
    name: 'Hannah Morales',
    email: 'hannah.stills@twbhub.internal',
    phone: '+1 (415) 555-0199',
    specialization: 'Photography',
    is_active: true,
    max_concurrent_projects: 4,
    notes: 'Lead Lightroom retoucher and album layout designer.',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c-1',
    company_id: 'twb',
    name: 'Sophia Sterling',
    partner_name: 'Liam Harrington',
    email: 'sophia.sterling@gmail.com',
    phone: '+1 (415) 877-3921',
    address: 'Pacific Heights, San Francisco, CA',
    instagram: '@sophia_sterling',
    notes: 'Black-tie Napa Valley vineyard wedding. High focus on cinematic soundscape.',
    created_at: '2026-06-10T10:00:00Z',
  },
  {
    id: 'c-2',
    company_id: 'golden_june',
    name: 'Maya Thornton',
    partner_name: 'Ethan Ross',
    email: 'maya.thornton@nycloft.org',
    phone: '+1 (212) 982-3401',
    address: 'Tribeca, New York, NY',
    instagram: '@mayaross_wedding',
    notes: 'Hudson Valley bohemian autumn wedding. Requested Super 8 & 35mm film mixed with digital.',
    created_at: '2026-06-15T14:30:00Z',
  },
  {
    id: 'c-3',
    company_id: 'twb',
    name: 'Elena Rostova',
    partner_name: 'James C. Bennett',
    email: 'elena.rostova@outlook.com',
    phone: '+1 (310) 459-8822',
    address: 'Beverly Hills, CA',
    instagram: '@elenabennett_est',
    notes: 'Multi-day wedding weekend at Villa Cimbrone, Ravello Italy.',
    created_at: '2026-07-01T09:15:00Z',
  },
  {
    id: 'c-4',
    company_id: 'golden_june',
    name: 'Rhea Kapoor',
    partner_name: 'Aryan Singhania',
    email: 'rhea.singhania@gmail.com',
    phone: '+1 (415) 609-2244',
    address: 'Presidio Terrace, San Francisco, CA',
    instagram: '@rhea_aryan_2026',
    notes: 'Grand 3-day celebrations: Sangeet, Ceremony and Reception with drone coverage.',
    created_at: '2026-07-12T11:00:00Z',
  },
  {
    id: 'c-5',
    company_id: 'twb',
    name: 'Olivia Vance',
    partner_name: 'Marcus Webb',
    email: 'olivia.vance@studio.co',
    phone: '+1 (206) 431-7788',
    address: 'Seattle, WA',
    instagram: '@olivia_marcus',
    notes: 'Intimate Olympic Peninsula cliffside vows with reception at private estate.',
    created_at: '2026-08-01T16:20:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-1',
    company_id: 'twb',
    client_id: 'c-1',
    name: 'Sophia & Liam • Meadowood Napa Valley',
    wedding_date_start: '2026-09-26',
    wedding_date_end: '2026-09-26',
    venue: 'Meadowood Napa Valley Estate',
    city: 'St. Helena, CA',
    client_contact: {
      phone: '+1 (415) 877-3921',
      email: 'sophia.sterling@gmail.com',
    },
    status: 'Pre-Production',
    package_name: 'The Sovereign Cinema & Stills Collection',
    package_details: '10 Hours 3x Cinematographers + 2x Photographers, Drone Coverage, 4K Master, 60s Reel, 6-min Feature Film, 800+ Retouched Stills, Heirloom Leather Album.',
    booking_amount: 6000,
    total_amount: 14500,
    notes: 'Planner: Simone Edwards Weddings. Drone permit secured with Napa County.',
    created_at: '2026-06-12T10:00:00Z',
  },
  {
    id: 'prj-2',
    company_id: 'golden_june',
    client_id: 'c-2',
    name: 'Maya & Ethan • Cedar Lakes Estate',
    wedding_date_start: '2026-10-03',
    wedding_date_end: '2026-10-04',
    venue: 'Cedar Lakes Estate Amphitheater',
    city: 'Port Jervis, NY',
    client_contact: {
      phone: '+1 (212) 982-3401',
      email: 'maya.thornton@nycloft.org',
    },
    status: 'Booked',
    package_name: 'The Golden Hour Heirloom Cinema & Analog Stills',
    package_details: '2-Day Coverage: Welcome Bonfire + Wedding Day. Super 8mm analog reel scan + 4K Digital Cinema + 35mm film photography package.',
    booking_amount: 5000,
    total_amount: 12800,
    notes: 'Analog film cartridges shipped to Kodak Lab NY. Acoustic trio ceremony music.',
    created_at: '2026-06-18T14:00:00Z',
  },
  {
    id: 'prj-3',
    company_id: 'twb',
    client_id: 'c-3',
    name: 'Elena & James • Villa Cimbrone Ravello',
    wedding_date_start: '2026-10-18',
    wedding_date_end: '2026-10-20',
    venue: 'Villa Cimbrone & Belmond Hotel Caruso',
    city: 'Ravello, Amalfi Coast, Italy',
    client_contact: {
      phone: '+1 (310) 459-8822',
      email: 'elena.rostova@outlook.com',
    },
    status: 'Booked',
    package_name: 'International Destination Masterwork',
    package_details: '3-Day Italian Destination Film & Photography. Rehearsal Dinner on private yacht, Full Wedding Day, Post-wedding sunrise shoot.',
    booking_amount: 10000,
    total_amount: 24000,
    notes: 'Flight itineraries booked for Alex & David. EU Carnet and drone permit issued.',
    created_at: '2026-07-05T09:00:00Z',
  },
  {
    id: 'prj-4',
    company_id: 'golden_june',
    client_id: 'c-4',
    name: 'Rhea & Aryan • SF Palace of Fine Arts & Ritz Half Moon Bay',
    wedding_date_start: '2026-09-19',
    wedding_date_end: '2026-09-21',
    venue: 'Ritz-Carlton Half Moon Bay & SF City Hall',
    city: 'Half Moon Bay, CA',
    client_contact: {
      phone: '+1 (415) 609-2244',
      email: 'rhea.singhania@gmail.com',
    },
    status: 'Shooting',
    package_name: 'Grand 3-Day Wedding Heritage Package',
    package_details: '3 Days: Mehendi / Sangeet / Baraat & Reception. 4 Cinematographers, 3 Photographers, Daily Express Social Reels.',
    booking_amount: 8000,
    total_amount: 21500,
    notes: 'Team briefing completed. High energy lighting setup requested for Sangeet.',
    created_at: '2026-07-15T11:00:00Z',
  },
  {
    id: 'prj-5',
    company_id: 'twb',
    client_id: 'c-5',
    name: 'Olivia & Marcus • Alderbrook Estate',
    wedding_date_start: '2026-08-22',
    wedding_date_end: '2026-08-22',
    venue: 'Alderbrook Resort & Hood Canal',
    city: 'Union, WA',
    client_contact: {
      phone: '+1 (206) 431-7788',
      email: 'olivia.vance@studio.co',
    },
    status: 'Editing',
    package_name: 'Pacific Northwest Editorial Cinema',
    package_details: '8 Hours Cinema + Drone + Stills. Ceremony on seaside dock, ambient natural audio.',
    booking_amount: 4500,
    total_amount: 9800,
    notes: 'Footage fully ingested and synced. Marcus Vance assigned to primary edit cut.',
    created_at: '2026-08-05T15:00:00Z',
  },
];

export const INITIAL_PROJECT_TEAM: ProjectTeamAssignment[] = [
  // Sophia & Liam (2026-09-26)
  {
    id: 'pt-1',
    project_id: 'prj-1',
    team_member_id: 'tm-1',
    role: 'Lead Cinematographer',
    assignment_date: '2026-09-26',
    notes: 'Arrive at Meadowood 9:00 AM for bride prep',
  },
  {
    id: 'pt-2',
    project_id: 'prj-1',
    team_member_id: 'tm-3',
    role: 'Second Cinematographer & Audio',
    assignment_date: '2026-09-26',
    notes: 'Groom prep & ceremony lav placement',
  },
  {
    id: 'pt-3',
    project_id: 'prj-1',
    team_member_id: 'tm-5',
    role: 'Camera Assistant & DIT',
    assignment_date: '2026-09-26',
    notes: 'Live offloading cards during dinner speeches',
  },

  // Maya & Ethan (2026-10-03 & 2026-10-04)
  {
    id: 'pt-4',
    project_id: 'prj-2',
    team_member_id: 'tm-2',
    role: 'Principal Editorial Photographer',
    assignment_date: '2026-10-03',
    notes: 'Welcome cocktail party coverage 5-9pm',
  },
  {
    id: 'pt-5',
    project_id: 'prj-2',
    team_member_id: 'tm-2',
    role: 'Principal Editorial Photographer',
    assignment_date: '2026-10-04',
    notes: 'Full wedding day coverage 11am-11pm',
  },
  {
    id: 'pt-6',
    project_id: 'prj-2',
    team_member_id: 'tm-4',
    role: 'Second Photographer & Drone Op',
    assignment_date: '2026-10-04',
    notes: 'Drone flyover during mountain vows',
  },

  // Rhea & Aryan (2026-09-19)
  {
    id: 'pt-7',
    project_id: 'prj-4',
    team_member_id: 'tm-1',
    role: 'Lead Cinematographer',
    assignment_date: '2026-09-19',
    notes: 'Sangeet at Ritz-Carlton 4pm-midnight',
  },
  {
    id: 'pt-8',
    project_id: 'prj-4',
    team_member_id: 'tm-3',
    role: 'Second Cinematographer',
    assignment_date: '2026-09-19',
    notes: 'Baraat handheld stabilizer coverage',
  },
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-1',
    company_id: 'twb',
    client_name: 'Camilla Dupont',
    partner_name: 'Lucas Wright',
    email: 'camilla.dupont@parisart.fr',
    phone: '+1 (415) 301-4499',
    event_date: '2026-11-14',
    venue: 'Filoli Historic House & Garden',
    lead_source: 'Instagram Editorial Feature',
    requirements: 'Editorial wedding film with vintage anamorphic lenses. High emphasis on evening candlelit party and live jazz band audio.',
    estimated_budget: 15000,
    status: 'New',
    follow_up_date: '2026-09-15',
    notes: 'Referred by florist Studio Mondine. Bride is creative director at art agency.',
    quotation_status: 'Draft',
    created_at: '2026-09-10T12:00:00Z',
  },
  {
    id: 'enq-2',
    company_id: 'golden_june',
    client_name: 'Isabella Rossi',
    partner_name: 'Matteo Ferrari',
    email: 'isabella.rossi@verona.it',
    phone: '+1 (212) 441-9988',
    event_date: '2026-12-05',
    venue: 'The Wythe Hotel Brooklyn',
    lead_source: 'Vogue Weddings Directory',
    requirements: 'Winter rooftop ceremony with warm Golden June film color grading and heirloom photo album.',
    estimated_budget: 11000,
    status: 'Meeting Scheduled',
    follow_up_date: '2026-09-18',
    notes: 'Zoom consultation booked for Thursday 3 PM EST.',
    quotation_status: 'Sent',
    created_at: '2026-09-08T15:20:00Z',
  },
  {
    id: 'enq-3',
    company_id: 'twb',
    client_name: 'Avery Jenkins',
    partner_name: 'Daniel Zhao',
    email: 'avery.jenkins@techfirm.io',
    phone: '+1 (650) 819-2044',
    event_date: '2027-01-23',
    venue: 'San Francisco City Hall & Bently Reserve',
    lead_source: 'Word of Mouth / Past Couple',
    requirements: 'Full day cinematography with drone and 4K ceremony multi-cam.',
    estimated_budget: 13500,
    status: 'Proposal Sent',
    follow_up_date: '2026-09-20',
    notes: 'Sent Custom Sovereign Package proposal with optional rehearsal dinner add-on.',
    quotation_status: 'Sent',
    created_at: '2026-08-30T10:00:00Z',
  },
  {
    id: 'enq-4',
    company_id: 'golden_june',
    client_name: 'Zoe Kravitz-Miller',
    partner_name: 'Gabriel Santos',
    email: 'zoe.santos@greenpoint.me',
    phone: '+1 (347) 902-1155',
    event_date: '2027-02-14',
    venue: 'Stone Mill at New York Botanical Garden',
    lead_source: 'Google Search Organic',
    requirements: 'Valentine weekend intimate celebration. 35mm film stills + 6-min romantic highlight film.',
    estimated_budget: 9500,
    status: 'Contacted',
    follow_up_date: '2026-09-16',
    notes: 'Followed up with Golden June Lookbook PDF.',
    quotation_status: 'Draft',
    created_at: '2026-09-02T16:45:00Z',
  },
];

export const INITIAL_PROJECT_DATA: ProjectData[] = [
  {
    id: 'pdata-1',
    project_id: 'prj-5',
    company_id: 'twb',
    category: 'Raw Footage',
    storage_location: 'G-Drive ArmorATD 4TB (Vault Bay 3)',
    folder_link: 'https://drive.google.com/drive/folders/twb-alderbrook-raw-01',
    description: 'Sony FX6 4K XAVC-I footage (Cards A1-A4, B1-B3). 890 GB checksum verified with ShotPut Pro.',
    status: 'Backed Up',
    responsible_person: 'Kai Tanaka',
    date_recorded: '2026-08-23',
    notes: 'Dual backup on Synology NAS Volume 2 / Projects / 2026 / Olivia-Marcus.',
  },
  {
    id: 'pdata-2',
    project_id: 'prj-5',
    company_id: 'twb',
    category: 'Photos',
    storage_location: 'Cloud Archive AWS Glacier / Backblaze B2',
    folder_link: 'https://dropbox.com/sh/twb-alderbrook-stills-raw',
    description: 'Raw CR3 files from Canon R5 and Leica M11. 3,420 exposures total.',
    status: 'Backed Up',
    responsible_person: 'Sarah Jenkins',
    date_recorded: '2026-08-23',
    notes: 'Uploaded to cloud storage for retoucher review.',
  },
  {
    id: 'pdata-3',
    project_id: 'prj-5',
    company_id: 'twb',
    category: 'Audio',
    storage_location: 'Dropbox Audio Masters / TWB 2026',
    folder_link: 'https://dropbox.com/sh/twb-alderbrook-audio-32bit',
    description: '32-bit float audio recordings from Zoom F3 & Tentacle Track E (Officiant, Groom, DJ board tap).',
    status: 'Received',
    responsible_person: 'David Patel',
    date_recorded: '2026-08-23',
    notes: 'Clear ceremony audio, zero clipping.',
  },
  {
    id: 'pdata-4',
    project_id: 'prj-5',
    company_id: 'twb',
    category: 'Music',
    storage_location: 'Musicbed & Marmoset Licensed Library',
    folder_link: 'https://musicbed.com/playlists/twb-alderbrook-score',
    description: 'Licensed commercial rights for "Evergreen Whispers" (Ambient Orchestral) & "Golden Horizons".',
    status: 'Received',
    responsible_person: 'Marcus Vance',
    date_recorded: '2026-08-28',
    notes: 'License certificates saved in Documents folder.',
  },
  {
    id: 'pdata-5',
    project_id: 'prj-1',
    company_id: 'twb',
    category: 'Client References',
    storage_location: 'Milanote Production Board',
    folder_link: 'https://milanote.com/b/twb-sophia-liam-moodboard',
    description: 'Couple moodboard, shot list, family formal chart, and timeline schedule from planner.',
    status: 'Received',
    responsible_person: 'Julian Montgomery',
    date_recorded: '2026-09-01',
    notes: 'Special request for vintage black-and-white portraits during sunset.',
  },
];

export const INITIAL_DELIVERABLES: Deliverable[] = [
  {
    id: 'del-1',
    project_id: 'prj-5',
    company_id: 'twb',
    deliverable_type: 'Teaser / Reel (60s)',
    assigned_editor_id: 'ed-3', // Tyler Brooks
    due_date: '2026-09-14',
    status: 'Submitted',
    priority: 'High',
    external_link: 'https://frame.io/player/twb-alderbrook-teaser-v2',
    notes: 'Cut for 9:16 Instagram format with dynamic cut on ceremony vows.',
    review_status: 'Pending Admin Quality Review',
    last_updated: '2026-09-11T14:30:00Z',
  },
  {
    id: 'del-2',
    project_id: 'prj-5',
    company_id: 'twb',
    deliverable_type: 'Highlight Film (4-5 mins)',
    assigned_editor_id: 'ed-1', // Marcus Vance
    due_date: '2026-09-28',
    status: 'In Progress',
    priority: 'High',
    external_link: 'https://frame.io/player/twb-alderbrook-highlight-assembly',
    notes: 'Rough cut assembled with synchronized multi-track audio.',
    review_status: 'Editor working on audio sweetening',
    last_updated: '2026-09-10T18:00:00Z',
  },
  {
    id: 'del-3',
    project_id: 'prj-5',
    company_id: 'twb',
    deliverable_type: 'Full Photo Gallery (800+)',
    assigned_editor_id: 'ed-4', // Hannah Morales
    due_date: '2026-09-22',
    status: 'In Progress',
    priority: 'Medium',
    external_link: 'https://pic-time.com/twb/alderbrook-culling',
    notes: 'Culling complete (820 selects). Color correction and skin retouch in progress.',
    review_status: 'On track for deadline',
    last_updated: '2026-09-09T11:00:00Z',
  },
  {
    id: 'del-4',
    project_id: 'prj-5',
    company_id: 'twb',
    deliverable_type: 'Full Ceremony Edit',
    assigned_editor_id: 'ed-1', // Marcus Vance
    due_date: '2026-10-05',
    status: 'Not Started',
    priority: 'Low',
    external_link: '',
    notes: 'Multi-cam switch for entire 28 minute ceremony.',
    review_status: 'Awaiting highlight film sign-off',
    last_updated: '2026-08-25T10:00:00Z',
  },
  {
    id: 'del-5',
    project_id: 'prj-4',
    company_id: 'golden_june',
    deliverable_type: 'Teaser / Reel (60s)',
    assigned_editor_id: 'ed-3', // Tyler Brooks
    due_date: '2026-09-23',
    status: 'Assigned',
    priority: 'Urgent',
    external_link: '',
    notes: 'Quick-turn Sangeet highlight to publish within 48 hours of event.',
    review_status: 'Awaiting raw card offload',
    last_updated: '2026-09-11T09:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    project_id: 'prj-1',
    company_id: 'twb',
    payment_date: '2026-06-12',
    amount: 6000,
    payment_mode: 'Bank Transfer',
    description: 'Initial Retainer Deposit for Meadowood Napa Wedding',
    receipt_number: 'REC-TWB-2026-089',
    created_at: '2026-06-12T10:30:00Z',
  },
  {
    id: 'pay-2',
    project_id: 'prj-2',
    company_id: 'golden_june',
    payment_date: '2026-06-18',
    amount: 5000,
    payment_mode: 'Credit Card',
    description: 'Booking retainer for Cedar Lakes Estate wedding weekend',
    receipt_number: 'REC-GJ-2026-041',
    created_at: '2026-06-18T14:40:00Z',
  },
  {
    id: 'pay-3',
    project_id: 'prj-3',
    company_id: 'twb',
    payment_date: '2026-07-05',
    amount: 10000,
    payment_mode: 'Bank Transfer',
    description: 'International destination retainer deposit (Villa Cimbrone)',
    receipt_number: 'REC-TWB-2026-104',
    created_at: '2026-07-05T09:45:00Z',
  },
  {
    id: 'pay-4',
    project_id: 'prj-4',
    company_id: 'golden_june',
    payment_date: '2026-07-15',
    amount: 8000,
    payment_mode: 'Bank Transfer',
    description: '50% Retainer payment for 3-Day Wedding Celebrations',
    receipt_number: 'REC-GJ-2026-052',
    created_at: '2026-07-15T11:20:00Z',
  },
  {
    id: 'pay-5',
    project_id: 'prj-5',
    company_id: 'twb',
    payment_date: '2026-08-05',
    amount: 4500,
    payment_mode: 'Credit Card',
    description: 'Booking deposit for Alderbrook Estate wedding',
    receipt_number: 'REC-TWB-2026-118',
    created_at: '2026-08-05T15:30:00Z',
  },
  {
    id: 'pay-6',
    project_id: 'prj-5',
    company_id: 'twb',
    payment_date: '2026-08-15',
    amount: 5300,
    payment_mode: 'Bank Transfer',
    description: 'Final balance payment for Alderbrook Estate wedding',
    receipt_number: 'REC-TWB-2026-127',
    created_at: '2026-08-15T10:00:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    project_id: 'prj-5',
    company_id: 'twb',
    expense_date: '2026-08-21',
    amount: 420,
    category: 'Crew Travel',
    description: 'Ferry tickets & mileage for crew to Olympic Peninsula',
    paid_to: 'Washington State Ferries & Fuel',
    created_at: '2026-08-21T18:00:00Z',
  },
  {
    id: 'exp-2',
    project_id: 'prj-5',
    company_id: 'twb',
    expense_date: '2026-08-22',
    amount: 650,
    category: 'Accommodations',
    description: 'Cabins near Hood Canal for 3-person production crew',
    paid_to: 'Alderbrook Waterfront Lodging',
    created_at: '2026-08-22T08:00:00Z',
  },
  {
    id: 'exp-3',
    project_id: 'prj-5',
    company_id: 'twb',
    expense_date: '2026-08-28',
    amount: 199,
    category: 'Music Licensing',
    description: 'Commercial film sync license for "Evergreen Whispers"',
    paid_to: 'Musicbed Inc.',
    created_at: '2026-08-28T11:00:00Z',
  },
  {
    id: 'exp-4',
    project_id: 'prj-5',
    company_id: 'twb',
    expense_date: '2026-09-01',
    amount: 1200,
    category: 'Editor Fee',
    description: 'Feature cut editing advance for Marcus Vance',
    paid_to: 'Marcus Vance Creative',
    created_at: '2026-09-01T14:00:00Z',
  },
  {
    id: 'exp-5',
    project_id: 'prj-3',
    company_id: 'twb',
    expense_date: '2026-08-10',
    amount: 2800,
    category: 'Crew Travel',
    description: 'Round-trip flights SFO to Rome (FCO) for 2 cinematographers',
    paid_to: 'Delta Air Lines / Air France',
    created_at: '2026-08-10T12:00:00Z',
  },
  {
    id: 'exp-6',
    project_id: 'prj-1',
    company_id: 'twb',
    expense_date: '2026-09-05',
    amount: 350,
    category: 'Equipment Rental',
    description: 'Cooke SP3 anamorphic prime lens rental for ceremony',
    paid_to: 'BorrowLenses San Carlos',
    created_at: '2026-09-05T09:30:00Z',
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    company_id: 'golden_june',
    project_id: 'prj-4',
    title: 'Wedding Shoot: Rhea & Aryan (Sangeet)',
    event_type: 'Wedding',
    start_time: '2026-09-19T15:00:00Z',
    end_time: '2026-09-19T23:30:00Z',
    location: 'Ritz-Carlton Half Moon Bay',
    notes: 'Alex Rivera & David Patel assigned',
    assigned_member_id: 'tm-1',
  },
  {
    id: 'evt-2',
    company_id: 'twb',
    project_id: 'prj-1',
    title: 'Wedding Day: Sophia & Liam',
    event_type: 'Wedding',
    start_time: '2026-09-26T09:00:00Z',
    end_time: '2026-09-26T22:30:00Z',
    location: 'Meadowood Napa Valley',
    notes: 'Alex Rivera, David Patel, Kai Tanaka',
    assigned_member_id: 'tm-1',
  },
  {
    id: 'evt-3',
    company_id: 'twb',
    title: 'Consultation: Camilla & Lucas',
    event_type: 'Meeting',
    start_time: '2026-09-15T17:00:00Z',
    end_time: '2026-09-15T18:00:00Z',
    location: 'Zoom Video Conference',
    notes: 'Review Filoli House proposal and aesthetic samples',
  },
  {
    id: 'evt-4',
    company_id: 'twb',
    project_id: 'prj-5',
    title: 'Deliverable Deadline: Teaser Reel (Olivia & Marcus)',
    event_type: 'Deliverable Deadline',
    start_time: '2026-09-14T18:00:00Z',
    end_time: '2026-09-14T19:00:00Z',
    location: 'TWB Internal Cloud',
    notes: 'Tyler Brooks editing 60s cut',
  },
  {
    id: 'evt-5',
    company_id: 'golden_june',
    project_id: 'prj-2',
    title: 'Wedding Shoot: Maya & Ethan (Cedar Lakes)',
    event_type: 'Wedding',
    start_time: '2026-10-03T14:00:00Z',
    end_time: '2026-10-04T23:00:00Z',
    location: 'Cedar Lakes Estate, Port Jervis NY',
    notes: 'Sarah Jenkins & Nina Chen assigned',
    assigned_member_id: 'tm-2',
  },
  {
    id: 'evt-6',
    company_id: 'twb',
    project_id: 'prj-1',
    title: 'Payment Reminder: Sophia & Liam Final Balance ($8,500)',
    event_type: 'Payment Reminder',
    start_time: '2026-09-12T09:00:00Z',
    end_time: '2026-09-12T10:00:00Z',
    location: 'Billing Portal',
    notes: 'Due 14 days before wedding date',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Deliverable Submitted for Review',
    message: 'Tyler Brooks submitted Teaser / Reel (60s) for Olivia & Marcus • Alderbrook Estate.',
    type: 'deliverable_status',
    read: false,
    link: 'deliverables',
    created_at: '2026-09-11T14:35:00Z',
  },
  {
    id: 'notif-2',
    title: 'New High-Value Enquiry',
    message: 'Camilla Dupont submitted an enquiry for Filoli Historic House wedding ($15,000 budget).',
    type: 'new_enquiry',
    read: false,
    link: 'enquiries',
    created_at: '2026-09-10T12:05:00Z',
  },
  {
    id: 'notif-3',
    title: 'Payment Due Warning',
    message: 'Sophia & Liam balance payment of $8,500 is due for Meadowood Napa wedding (2 weeks away).',
    type: 'payment_overdue',
    read: false,
    link: 'finance',
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'notif-4',
    title: 'Payment Received ($5,300)',
    message: 'Final balance payment received for Olivia & Marcus (Alderbrook Estate) via Bank Transfer.',
    type: 'payment_received',
    read: true,
    link: 'finance',
    created_at: '2026-08-15T10:05:00Z',
  },
];
